package model;

 enum MonsterEffectEnum
{
    TRICKY,
    TERRATIGER,
    EXPLODERDRAGON,
    COMMANDKNIGHT,
    TERRATIGERTHEEMPOWEREDWARRIOR,
    EXPLODERDRAGON,
    HERALDOFCREATION,
    MIRAGEDRAGON,
    THECALCULATOR,
    TEXCHANGER,
    BEASTKINGBARBAROS,
    MARSHMALLON,
    SCANNER,
    GATEGUARDIAN,
    MANEATERBUG
}
