package model;

 enum MonsterEnum
{
    BATTLEOX,
    AXERAIDER,
    HORNIMP,
    SILVERFANG,
    FIREYAROU,
    CURTAINOFDARKONES,
    FERALIMP,
    DARKMAGICIAN,
    WATTKID,
    BABYDRAGON,
    HEROOFTHEEAST,
    BATTLEWARRIOR,
    CRAWLINGDRAGON,
    FLAMEMANIPULATOR,
    BLUEEYESWHITEDRAGON,
    SLOTMACHINE,
    HANIWA,
    BITRON,
    LEOTRONALEXANDRITEDRAGON,
    WARRIORDAIGREPHER,
    DARKBLADE,
    WATTAILDRAGON,
    SPIRALSERPENT
}
