package model;

enum SpellEnum {
    MONSTERREBORN,
    TERRAFORMING,
    POTOFGREED,
    ADVANCEDRITUALART,
    TWINTWISTERS,
    MYSTICALSPACETYPHOON,
    RINGOFDEFENSE,
    YAMI,
    FOREST,
    CLOSEDFOREST,
    UMIIRUKA,
    SWORDOFDARKDESTRUCTION,
    BLACKPENDANT,
    UNITEDWESTAND,
    MAGNUMSHIELD,
    RAIGEKI,
    CHANGEOFHEART,
    HARPIESFEATHERDUSTER,
    DARKHOLE,
    SUPPLYSQUAD,
    SWORDSOFREVEALINGLIGHT,
    SPELLABSORPTION,
    MESSENGEROFPEACE
}
