package model;

public enum TrapType {
    MAGICCYLINDER,
    MIRRORFORCE,
    MINDCRUSH,
    TRAPHOLE,
    TORRENTIALTRIBUTE,
    TIMESEAL,
    NEGATEATTACK,
    SOLEMNWARNING,
    MAGICJAMMER,
    CALLOFTHEHAUNTED
}
