package model.commands;

public enum ShopCommandType {
    BUY_CARD,
    SELECT_CARD,
    GET_SHOP_CARDS,
    UPDATE_NUMBER_OF_AVAILABLE_CARDS,
    INCREASE,
    DECREASE,
    FORBID_BUYING,
    START_BUYING,
    GET_ACTIVE_AUCTIONS,
    MAKE_NEW_AUCTION,
    ENTER_ACTIVE_AUCTIONS,
    DELETE_AUCTION,
    NEW_BID_IN_AUCTION,
    OPEN_SELECTED_AUCTION,
    UPDATE_AUCTION
}
